import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation files
const translationData = {
  en: {
    // Navigation
    'nav.signIn': 'Sign In',
    'nav.joinATRC': 'Join ATRC',
    'nav.dashboard': 'Dashboard',
    'nav.communities': 'Communities',
    'nav.disputes': 'Disputes',
    'nav.events': 'Events',
    'nav.announcements': 'Announcements',
    'nav.reports': 'Reports',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    
    // Homepage
    'home.title': 'African Traditional',
    'home.subtitle': 'Rulers Council',
    'home.description': 'Empowering traditional rulers with modern digital tools for community governance, dispute resolution, and cultural preservation across Africa.',
    'home.joinCommunity': 'Join Our Community',
    'home.signIn': 'Sign In',
    
    // Stats
    'stats.communities': 'Traditional Communities',
    'stats.rulers': 'Active Rulers',
    'stats.members': 'Community Members',
    'stats.support': 'Support Available',
    
    // Features
    'features.title': 'Digital Tools for Traditional Governance',
    'features.subtitle': 'Modern technology solutions designed specifically for African traditional rulers and communities',
    'features.community.title': 'Community Management',
    'features.community.desc': 'Manage traditional communities and kingdoms with digital tools',
    'features.disputes.title': 'Dispute Resolution',
    'features.disputes.desc': 'Traditional dispute resolution system with mediation tools',
    'features.events.title': 'Event Management',
    'features.events.desc': 'Organize cultural events and traditional ceremonies',
    'features.announcements.title': 'Announcements',
    'features.announcements.desc': 'Communicate important updates to community members',
    'features.analytics.title': 'Analytics & Reports',
    'features.analytics.desc': 'Comprehensive reporting and community insights',
    'features.members.title': 'Member Management',
    'features.members.desc': 'Manage community members and traditional roles',
    
    // CTA
    'cta.title': 'Ready to Join the Digital Revolution?',
    'cta.subtitle': 'Connect with traditional rulers across Africa and modernize your community governance',
    'cta.getStarted': 'Get Started Today',
    
    // Footer
    'footer.description': 'Empowering traditional rulers with modern digital tools for community governance, dispute resolution, and cultural preservation.',
    'footer.features': 'Features',
    'footer.support': 'Support',
    'footer.helpCenter': 'Help Center',
    'footer.contactUs': 'Contact Us',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.copyright': '© 2024 African Traditional Rulers Council. All rights reserved.',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.rulerSubtitle': 'Traditional Rulers Dashboard',
    'dashboard.adminWelcome': 'Welcome',
    'dashboard.adminSubtitle': 'System Administration Dashboard',
    'dashboard.myCommunities': 'My Communities',
    'dashboard.totalRulers': 'Total Rulers',
    'dashboard.totalCommunities': 'Total Communities',
    'dashboard.activeDisputes': 'Active Disputes',
    'dashboard.systemDisputes': 'System Disputes',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.totalMembers': 'Total Members',
    'dashboard.pendingApprovals': 'Pending Approvals',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.adminActions': 'Administrative Actions',
    'dashboard.manageCommunities': 'Manage Communities',
    'dashboard.manageCommunitiesDesc': 'Add, edit, or view traditional communities',
    'dashboard.resolveDisputes': 'Resolve Disputes',
    'dashboard.resolveDisputesDesc': 'Handle traditional dispute resolution',
    'dashboard.planEvents': 'Plan Events',
    'dashboard.planEventsDesc': 'Organize cultural events and ceremonies',
    'dashboard.sendAnnouncements': 'Send Announcements',
    'dashboard.sendAnnouncementsDesc': 'Communicate with community members',
    'dashboard.viewReports': 'View Reports',
    'dashboard.viewReportsDesc': 'Access analytics and reports',
    'dashboard.manageProfile': 'Manage Profile',
    'dashboard.manageProfileDesc': 'Update your profile information',
    'dashboard.manageRulers': 'Manage Rulers',
    'dashboard.manageRulersDesc': 'Approve and manage traditional rulers',
    'dashboard.systemDisputesDesc': 'Handle system-wide dispute resolution',
    'dashboard.userManagement': 'User Management',
    'dashboard.userManagementDesc': 'Manage system users and permissions',
    'dashboard.systemSettings': 'System Settings',
    'dashboard.systemSettingsDesc': 'Configure system-wide settings',
    'dashboard.analytics': 'Analytics',
    'dashboard.analyticsDesc': 'View system analytics and insights',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.systemAlerts': 'System Alerts',
    'dashboard.recentSystemActivity': 'Recent System Activity',
    'dashboard.newDisputeActivity': 'New dispute filed by Chief Adebayo',
    'dashboard.culturalFestivalActivity': 'Cultural festival scheduled for next month',
    'dashboard.newMembersActivity': '5 new members joined the community',
    'dashboard.highPriorityDispute': 'High priority dispute requires attention',
    'dashboard.requiresImmediate': 'Requires immediate review',
    'dashboard.pendingRulerApproval': 'New ruler application pending approval',
    'dashboard.awaitingReview': 'Awaiting administrative review',
    'dashboard.systemMaintenance': 'System maintenance scheduled',
    'dashboard.scheduledTonight': 'Scheduled for tonight at 2 AM',
    'dashboard.newRulerApproved': 'New ruler application approved',
    'dashboard.newCommunityRegistered': 'New community registered in system',
    'dashboard.bulkUserImport': 'Bulk user import completed',
    'dashboard.completedSuccessfully': 'Completed successfully',
    'dashboard.twoHoursAgo': '2 hours ago',
    'dashboard.oneHourAgo': '1 hour ago',
    'dashboard.oneDayAgo': '1 day ago',
    'dashboard.threeDaysAgo': '3 days ago',
    
    // Community Management
    'community.title': 'Community Management',
    'community.subtitle': 'Manage traditional communities and kingdoms',
    'community.loading': 'Loading communities...',
    'community.traditionalCommunities': 'Traditional Communities',
    'community.addNew': 'Add New',
    'community.addNewCommunity': 'Add New Community',
    'community.addCommunity': 'Add Community',
    'community.editCommunity': 'Edit Community',
    'community.name': 'Community Name',
    'community.ruler': 'Ruler',
    'community.location': 'Location',
    'community.description': 'Description',
    'community.status': 'Status',
    'community.active': 'Active',
    'community.inactive': 'Inactive',
    'community.members': 'members',
    'community.add': 'Add',
    'community.update': 'Update',
    'community.cancel': 'Cancel',
    'community.edit': 'Edit',
    'community.delete': 'Delete',
    'community.confirmDelete': 'Are you sure you want to delete this community?',
    'community.noCommunities': 'No communities found. Add your first community to get started.',
    'community.quickActions': 'Quick Actions',
    'community.importCommunities': 'Import Communities',
    'community.generateReport': 'Generate Report',
    'community.statistics': 'Statistics',
    'community.totalCommunities': 'Total Communities',
    'community.totalMembers': 'Total Members',
    'community.activeCommunities': 'Active Communities',
    
    // Language
    'language.english': 'English',
    'language.french': 'Français',
    'language.spanish': 'Español',
    'language.arabic': 'العربية',
    'language.swahili': 'Kiswahili',
    'language.yoruba': 'Yorùbá',
    'language.igbo': 'Igbo',
    'language.hausa': 'Hausa',
  },
  
  fr: {
    // Navigation
    'nav.signIn': 'Se connecter',
    'nav.joinATRC': 'Rejoindre ATRC',
    'nav.dashboard': 'Tableau de bord',
    'nav.communities': 'Communautés',
    'nav.disputes': 'Litiges',
    'nav.events': 'Événements',
    'nav.announcements': 'Annonces',
    'nav.reports': 'Rapports',
    'nav.profile': 'Profil',
    'nav.settings': 'Paramètres',
    'nav.logout': 'Déconnexion',
    
    // Homepage
    'home.title': 'Conseil des Dirigeants',
    'home.subtitle': 'Traditionnels Africains',
    'home.description': 'Autonomiser les dirigeants traditionnels avec des outils numériques modernes pour la gouvernance communautaire, la résolution de conflits et la préservation culturelle à travers l\'Afrique.',
    'home.joinCommunity': 'Rejoindre notre communauté',
    'home.signIn': 'Se connecter',
    
    // Stats
    'stats.communities': 'Communautés traditionnelles',
    'stats.rulers': 'Dirigeants actifs',
    'stats.members': 'Membres de la communauté',
    'stats.support': 'Support disponible',
    
    // Features
    'features.title': 'Outils numériques pour la gouvernance traditionnelle',
    'features.subtitle': 'Solutions technologiques modernes conçues spécifiquement pour les dirigeants traditionnels africains et leurs communautés',
    'features.community.title': 'Gestion communautaire',
    'features.community.desc': 'Gérer les communautés et royaumes traditionnels avec des outils numériques',
    'features.disputes.title': 'Résolution de conflits',
    'features.disputes.desc': 'Système traditionnel de résolution de conflits avec outils de médiation',
    'features.events.title': 'Gestion d\'événements',
    'features.events.desc': 'Organiser des événements culturels et cérémonies traditionnelles',
    'features.announcements.title': 'Annonces',
    'features.announcements.desc': 'Communiquer les mises à jour importantes aux membres de la communauté',
    'features.analytics.title': 'Analyses et rapports',
    'features.analytics.desc': 'Rapports complets et insights communautaires',
    'features.members.title': 'Gestion des membres',
    'features.members.desc': 'Gérer les membres de la communauté et les rôles traditionnels',
    
    // CTA
    'cta.title': 'Prêt à rejoindre la révolution numérique ?',
    'cta.subtitle': 'Connectez-vous avec les dirigeants traditionnels à travers l\'Afrique et modernisez votre gouvernance communautaire',
    'cta.getStarted': 'Commencer aujourd\'hui',
    
    // Footer
    'footer.description': 'Autonomiser les dirigeants traditionnels avec des outils numériques modernes pour la gouvernance communautaire, la résolution de conflits et la préservation culturelle.',
    'footer.features': 'Fonctionnalités',
    'footer.support': 'Support',
    'footer.helpCenter': 'Centre d\'aide',
    'footer.contactUs': 'Nous contacter',
    'footer.privacyPolicy': 'Politique de confidentialité',
    'footer.termsOfService': 'Conditions d\'utilisation',
    'footer.copyright': '© 2024 Conseil des Dirigeants Traditionnels Africains. Tous droits réservés.',
    
    // Dashboard
    'dashboard.welcome': 'Bon retour',
    'dashboard.rulerSubtitle': 'Tableau de bord des Dirigeants Traditionnels',
    'dashboard.adminWelcome': 'Bienvenue',
    'dashboard.adminSubtitle': 'Tableau de bord d\'Administration Système',
    'dashboard.myCommunities': 'Mes Communautés',
    'dashboard.totalRulers': 'Total Dirigeants',
    'dashboard.totalCommunities': 'Total Communautés',
    'dashboard.activeDisputes': 'Litiges Actifs',
    'dashboard.systemDisputes': 'Litiges Système',
    'dashboard.upcomingEvents': 'Événements à Venir',
    'dashboard.totalMembers': 'Total Membres',
    'dashboard.pendingApprovals': 'Approbations en Attente',
    'dashboard.quickActions': 'Actions Rapides',
    'dashboard.adminActions': 'Actions Administratives',
    'dashboard.manageCommunities': 'Gérer les Communautés',
    'dashboard.manageCommunitiesDesc': 'Ajouter, modifier ou voir les communautés traditionnelles',
    'dashboard.resolveDisputes': 'Résoudre les Litiges',
    'dashboard.resolveDisputesDesc': 'Gérer la résolution traditionnelle de conflits',
    'dashboard.planEvents': 'Planifier les Événements',
    'dashboard.planEventsDesc': 'Organiser des événements culturels et cérémonies',
    'dashboard.sendAnnouncements': 'Envoyer des Annonces',
    'dashboard.sendAnnouncementsDesc': 'Communiquer avec les membres de la communauté',
    'dashboard.viewReports': 'Voir les Rapports',
    'dashboard.viewReportsDesc': 'Accéder aux analyses et rapports',
    'dashboard.manageProfile': 'Gérer le Profil',
    'dashboard.manageProfileDesc': 'Mettre à jour vos informations de profil',
    'dashboard.manageRulers': 'Gérer les Dirigeants',
    'dashboard.manageRulersDesc': 'Approuver et gérer les dirigeants traditionnels',
    'dashboard.systemDisputesDesc': 'Gérer la résolution de conflits à l\'échelle du système',
    'dashboard.userManagement': 'Gestion des Utilisateurs',
    'dashboard.userManagementDesc': 'Gérer les utilisateurs du système et permissions',
    'dashboard.systemSettings': 'Paramètres Système',
    'dashboard.systemSettingsDesc': 'Configurer les paramètres à l\'échelle du système',
    'dashboard.analytics': 'Analyses',
    'dashboard.analyticsDesc': 'Voir les analyses et insights du système',
    'dashboard.recentActivity': 'Activité Récente',
    'dashboard.systemAlerts': 'Alertes Système',
    'dashboard.recentSystemActivity': 'Activité Système Récente',
    'dashboard.newDisputeActivity': 'Nouveau litige déposé par Chef Adebayo',
    'dashboard.culturalFestivalActivity': 'Festival culturel programmé pour le mois prochain',
    'dashboard.newMembersActivity': '5 nouveaux membres ont rejoint la communauté',
    'dashboard.highPriorityDispute': 'Litige haute priorité nécessite attention',
    'dashboard.requiresImmediate': 'Nécessite une révision immédiate',
    'dashboard.pendingRulerApproval': 'Nouvelle candidature de dirigeant en attente d\'approbation',
    'dashboard.awaitingReview': 'En attente de révision administrative',
    'dashboard.systemMaintenance': 'Maintenance système programmée',
    'dashboard.scheduledTonight': 'Programmée pour ce soir à 2h',
    'dashboard.newRulerApproved': 'Nouvelle candidature de dirigeant approuvée',
    'dashboard.newCommunityRegistered': 'Nouvelle communauté enregistrée dans le système',
    'dashboard.bulkUserImport': 'Import en masse d\'utilisateurs terminé',
    'dashboard.completedSuccessfully': 'Terminé avec succès',
    'dashboard.twoHoursAgo': 'Il y a 2 heures',
    'dashboard.oneHourAgo': 'Il y a 1 heure',
    'dashboard.oneDayAgo': 'Il y a 1 jour',
    'dashboard.threeDaysAgo': 'Il y a 3 jours',
    
    // Community Management
    'community.title': 'Gestion des Communautés',
    'community.subtitle': 'Gérer les communautés et royaumes traditionnels',
    'community.loading': 'Chargement des communautés...',
    'community.traditionalCommunities': 'Communautés Traditionnelles',
    'community.addNew': 'Ajouter Nouveau',
    'community.addNewCommunity': 'Ajouter Nouvelle Communauté',
    'community.addCommunity': 'Ajouter Communauté',
    'community.editCommunity': 'Modifier Communauté',
    'community.name': 'Nom de la Communauté',
    'community.ruler': 'Dirigeant',
    'community.location': 'Localisation',
    'community.description': 'Description',
    'community.status': 'Statut',
    'community.active': 'Actif',
    'community.inactive': 'Inactif',
    'community.members': 'membres',
    'community.add': 'Ajouter',
    'community.update': 'Mettre à jour',
    'community.cancel': 'Annuler',
    'community.edit': 'Modifier',
    'community.delete': 'Supprimer',
    'community.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cette communauté ?',
    'community.noCommunities': 'Aucune communauté trouvée. Ajoutez votre première communauté pour commencer.',
    'community.quickActions': 'Actions Rapides',
    'community.importCommunities': 'Importer Communautés',
    'community.generateReport': 'Générer Rapport',
    'community.statistics': 'Statistiques',
    'community.totalCommunities': 'Total Communautés',
    'community.totalMembers': 'Total Membres',
    'community.activeCommunities': 'Communautés Actives',
    
    // Language
    'language.english': 'English',
    'language.french': 'Français',
    'language.spanish': 'Español',
    'language.arabic': 'العربية',
    'language.swahili': 'Kiswahili',
    'language.yoruba': 'Yorùbá',
    'language.igbo': 'Igbo',
    'language.hausa': 'Hausa',
  },
  
  es: {
    // Navigation
    'nav.signIn': 'Iniciar sesión',
    'nav.joinATRC': 'Unirse a ATRC',
    'nav.dashboard': 'Panel de control',
    'nav.communities': 'Comunidades',
    'nav.disputes': 'Disputas',
    'nav.events': 'Eventos',
    'nav.announcements': 'Anuncios',
    'nav.reports': 'Informes',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configuración',
    'nav.logout': 'Cerrar sesión',
    
    // Homepage
    'home.title': 'Consejo de Líderes',
    'home.subtitle': 'Tradicionales Africanos',
    'home.description': 'Empoderando a los líderes tradicionales con herramientas digitales modernas para la gobernanza comunitaria, resolución de disputas y preservación cultural en toda África.',
    'home.joinCommunity': 'Únete a nuestra comunidad',
    'home.signIn': 'Iniciar sesión',
    
    // Stats
    'stats.communities': 'Comunidades tradicionales',
    'stats.rulers': 'Líderes activos',
    'stats.members': 'Miembros de la comunidad',
    'stats.support': 'Soporte disponible',
    
    // Features
    'features.title': 'Herramientas digitales para la gobernanza tradicional',
    'features.subtitle': 'Soluciones tecnológicas modernas diseñadas específicamente para líderes tradicionales africanos y sus comunidades',
    'features.community.title': 'Gestión comunitaria',
    'features.community.desc': 'Gestionar comunidades y reinos tradicionales con herramientas digitales',
    'features.disputes.title': 'Resolución de disputas',
    'features.disputes.desc': 'Sistema tradicional de resolución de disputas con herramientas de mediación',
    'features.events.title': 'Gestión de eventos',
    'features.events.desc': 'Organizar eventos culturales y ceremonias tradicionales',
    'features.announcements.title': 'Anuncios',
    'features.announcements.desc': 'Comunicar actualizaciones importantes a los miembros de la comunidad',
    'features.analytics.title': 'Análisis e informes',
    'features.analytics.desc': 'Informes completos e insights comunitarios',
    'features.members.title': 'Gestión de miembros',
    'features.members.desc': 'Gestionar miembros de la comunidad y roles tradicionales',
    
    // CTA
    'cta.title': '¿Listo para unirte a la revolución digital?',
    'cta.subtitle': 'Conéctate con líderes tradicionales en toda África y moderniza tu gobernanza comunitaria',
    'cta.getStarted': 'Comenzar hoy',
    
    // Footer
    'footer.description': 'Empoderando a los líderes tradicionales con herramientas digitales modernas para la gobernanza comunitaria, resolución de disputas y preservación cultural.',
    'footer.features': 'Características',
    'footer.support': 'Soporte',
    'footer.helpCenter': 'Centro de ayuda',
    'footer.contactUs': 'Contáctanos',
    'footer.privacyPolicy': 'Política de privacidad',
    'footer.termsOfService': 'Términos de servicio',
    'footer.copyright': '© 2024 Consejo de Líderes Tradicionales Africanos. Todos los derechos reservados.',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido de vuelta',
    'dashboard.rulerSubtitle': 'Panel de Líderes Tradicionales',
    'dashboard.adminWelcome': 'Bienvenido',
    'dashboard.adminSubtitle': 'Panel de Administración del Sistema',
    'dashboard.myCommunities': 'Mis Comunidades',
    'dashboard.totalRulers': 'Total Líderes',
    'dashboard.totalCommunities': 'Total Comunidades',
    'dashboard.activeDisputes': 'Disputas Activas',
    'dashboard.systemDisputes': 'Disputas del Sistema',
    'dashboard.upcomingEvents': 'Eventos Próximos',
    'dashboard.totalMembers': 'Total Miembros',
    'dashboard.pendingApprovals': 'Aprobaciones Pendientes',
    'dashboard.quickActions': 'Acciones Rápidas',
    'dashboard.adminActions': 'Acciones Administrativas',
    'dashboard.manageCommunities': 'Gestionar Comunidades',
    'dashboard.manageCommunitiesDesc': 'Agregar, editar o ver comunidades tradicionales',
    'dashboard.resolveDisputes': 'Resolver Disputas',
    'dashboard.resolveDisputesDesc': 'Manejar resolución tradicional de disputas',
    'dashboard.planEvents': 'Planificar Eventos',
    'dashboard.planEventsDesc': 'Organizar eventos culturales y ceremonias',
    'dashboard.sendAnnouncements': 'Enviar Anuncios',
    'dashboard.sendAnnouncementsDesc': 'Comunicarse con miembros de la comunidad',
    'dashboard.viewReports': 'Ver Informes',
    'dashboard.viewReportsDesc': 'Acceder a análisis e informes',
    'dashboard.manageProfile': 'Gestionar Perfil',
    'dashboard.manageProfileDesc': 'Actualizar información de perfil',
    'dashboard.manageRulers': 'Gestionar Líderes',
    'dashboard.manageRulersDesc': 'Aprobar y gestionar líderes tradicionales',
    'dashboard.systemDisputesDesc': 'Manejar resolución de disputas a nivel del sistema',
    'dashboard.userManagement': 'Gestión de Usuarios',
    'dashboard.userManagementDesc': 'Gestionar usuarios del sistema y permisos',
    'dashboard.systemSettings': 'Configuración del Sistema',
    'dashboard.systemSettingsDesc': 'Configurar ajustes a nivel del sistema',
    'dashboard.analytics': 'Análisis',
    'dashboard.analyticsDesc': 'Ver análisis e insights del sistema',
    'dashboard.recentActivity': 'Actividad Reciente',
    'dashboard.systemAlerts': 'Alertas del Sistema',
    'dashboard.recentSystemActivity': 'Actividad Reciente del Sistema',
    'dashboard.newDisputeActivity': 'Nueva disputa presentada por Jefe Adebayo',
    'dashboard.culturalFestivalActivity': 'Festival cultural programado para el próximo mes',
    'dashboard.newMembersActivity': '5 nuevos miembros se unieron a la comunidad',
    'dashboard.highPriorityDispute': 'Disputa de alta prioridad requiere atención',
    'dashboard.requiresImmediate': 'Requiere revisión inmediata',
    'dashboard.pendingRulerApproval': 'Nueva aplicación de líder pendiente de aprobación',
    'dashboard.awaitingReview': 'Esperando revisión administrativa',
    'dashboard.systemMaintenance': 'Mantenimiento del sistema programado',
    'dashboard.scheduledTonight': 'Programado para esta noche a las 2 AM',
    'dashboard.newRulerApproved': 'Nueva aplicación de líder aprobada',
    'dashboard.newCommunityRegistered': 'Nueva comunidad registrada en el sistema',
    'dashboard.bulkUserImport': 'Importación masiva de usuarios completada',
    'dashboard.completedSuccessfully': 'Completado exitosamente',
    'dashboard.twoHoursAgo': 'Hace 2 horas',
    'dashboard.oneHourAgo': 'Hace 1 hora',
    'dashboard.oneDayAgo': 'Hace 1 día',
    'dashboard.threeDaysAgo': 'Hace 3 días',
    
    // Community Management
    'community.title': 'Gestión de Comunidades',
    'community.subtitle': 'Gestionar comunidades y reinos tradicionales',
    'community.loading': 'Cargando comunidades...',
    'community.traditionalCommunities': 'Comunidades Tradicionales',
    'community.addNew': 'Agregar Nuevo',
    'community.addNewCommunity': 'Agregar Nueva Comunidad',
    'community.addCommunity': 'Agregar Comunidad',
    'community.editCommunity': 'Editar Comunidad',
    'community.name': 'Nombre de la Comunidad',
    'community.ruler': 'Líder',
    'community.location': 'Ubicación',
    'community.description': 'Descripción',
    'community.status': 'Estado',
    'community.active': 'Activo',
    'community.inactive': 'Inactivo',
    'community.members': 'miembros',
    'community.add': 'Agregar',
    'community.update': 'Actualizar',
    'community.cancel': 'Cancelar',
    'community.edit': 'Editar',
    'community.delete': 'Eliminar',
    'community.confirmDelete': '¿Estás seguro de que quieres eliminar esta comunidad?',
    'community.noCommunities': 'No se encontraron comunidades. Agrega tu primera comunidad para comenzar.',
    'community.quickActions': 'Acciones Rápidas',
    'community.importCommunities': 'Importar Comunidades',
    'community.generateReport': 'Generar Informe',
    'community.statistics': 'Estadísticas',
    'community.totalCommunities': 'Total Comunidades',
    'community.totalMembers': 'Total Miembros',
    'community.activeCommunities': 'Comunidades Activas',
    
    // Language
    'language.english': 'English',
    'language.french': 'Français',
    'language.spanish': 'Español',
    'language.arabic': 'العربية',
    'language.swahili': 'Kiswahili',
    'language.yoruba': 'Yorùbá',
    'language.igbo': 'Igbo',
    'language.hausa': 'Hausa',
  },
  
  sw: {
    // Navigation
    'nav.signIn': 'Ingia',
    'nav.joinATRC': 'Jiunge na ATRC',
    'nav.dashboard': 'Dashibodi',
    'nav.communities': 'Jamii',
    'nav.disputes': 'Migogoro',
    'nav.events': 'Matukio',
    'nav.announcements': 'Matangazo',
    'nav.reports': 'Ripoti',
    'nav.profile': 'Wasifu',
    'nav.settings': 'Mipangilio',
    'nav.logout': 'Ondoka',
    
    // Homepage
    'home.title': 'Baraza la Viongozi',
    'home.subtitle': 'Wa Jadi wa Kiafrika',
    'home.description': 'Kuwawezesha viongozi wa jadi kwa vifaa vya kidijitali vya kisasa kwa utawala wa jamii, utatuzi wa migogoro, na uhifadhi wa utamaduni katika Afrika.',
    'home.joinCommunity': 'Jiunge na jamii yetu',
    'home.signIn': 'Ingia',
    
    // Stats
    'stats.communities': 'Jamii za jadi',
    'stats.rulers': 'Viongozi hai',
    'stats.members': 'Wanajamii',
    'stats.support': 'Msaada unapatikana',
    
    // Features
    'features.title': 'Vifaa vya kidijitali kwa utawala wa jadi',
    'features.subtitle': 'Suluhisho za teknolojia za kisasa zilizoundwa mahsusi kwa viongozi wa jadi wa Kiafrika na jamii zao',
    'features.community.title': 'Usimamizi wa jamii',
    'features.community.desc': 'Simamia jamii na falme za jadi kwa vifaa vya kidijitali',
    'features.disputes.title': 'Utatuzi wa migogoro',
    'features.disputes.desc': 'Mfumo wa jadi wa utatuzi wa migogoro na vifaa vya upatanishi',
    'features.events.title': 'Usimamizi wa matukio',
    'features.events.desc': 'Panga matukio ya kitamaduni na sherehe za jadi',
    'features.announcements.title': 'Matangazo',
    'features.announcements.desc': 'Wasiliana mabadiliko muhimu kwa wanajamii',
    'features.analytics.title': 'Uchambuzi na ripoti',
    'features.analytics.desc': 'Ripoti kamili na maarifa ya jamii',
    'features.members.title': 'Usimamizi wa wanachama',
    'features.members.desc': 'Simamia wanajamii na majukumu ya jadi',
    
    // CTA
    'cta.title': 'Uko tayari kujiunga na mapinduzi ya kidijitali?',
    'cta.subtitle': 'Ungana na viongozi wa jadi katika Afrika na kubadilisha utawala wako wa jamii',
    'cta.getStarted': 'Anza leo',
    
    // Footer
    'footer.description': 'Kuwawezesha viongozi wa jadi kwa vifaa vya kidijitali vya kisasa kwa utawala wa jamii, utatuzi wa migogoro, na uhifadhi wa utamaduni.',
    'footer.features': 'Vipengele',
    'footer.support': 'Msaada',
    'footer.helpCenter': 'Kituo cha msaada',
    'footer.contactUs': 'Wasiliana nasi',
    'footer.privacyPolicy': 'Sera ya faragha',
    'footer.termsOfService': 'Masharti ya huduma',
    'footer.copyright': '© 2024 Baraza la Viongozi wa Jadi wa Kiafrika. Haki zote zimehifadhiwa.',
    
    // Dashboard
    'dashboard.welcome': 'Karibu tena',
    'dashboard.rulerSubtitle': 'Dashibodi ya Viongozi wa Jadi',
    'dashboard.adminWelcome': 'Karibu',
    'dashboard.adminSubtitle': 'Dashibodi ya Utawala wa Mfumo',
    'dashboard.myCommunities': 'Jamii Zangu',
    'dashboard.totalRulers': 'Jumla ya Viongozi',
    'dashboard.totalCommunities': 'Jumla ya Jamii',
    'dashboard.activeDisputes': 'Migogoro Hai',
    'dashboard.systemDisputes': 'Migogoro ya Mfumo',
    'dashboard.upcomingEvents': 'Matukio Yanayokuja',
    'dashboard.totalMembers': 'Jumla ya Wanachama',
    'dashboard.pendingApprovals': 'Idhini za Kusubiri',
    'dashboard.quickActions': 'Vitendo vya Haraka',
    'dashboard.adminActions': 'Vitendo vya Utawala',
    'dashboard.manageCommunities': 'Simamia Jamii',
    'dashboard.manageCommunitiesDesc': 'Ongeza, hariri au ona jamii za jadi',
    'dashboard.resolveDisputes': 'Suluhisha Migogoro',
    'dashboard.resolveDisputesDesc': 'Shughulikia utatuzi wa jadi wa migogoro',
    'dashboard.planEvents': 'Panga Matukio',
    'dashboard.planEventsDesc': 'Panga matukio ya kitamaduni na sherehe',
    'dashboard.sendAnnouncements': 'Tuma Matangazo',
    'dashboard.sendAnnouncementsDesc': 'Wasiliana na wanajamii',
    'dashboard.viewReports': 'Ona Ripoti',
    'dashboard.viewReportsDesc': 'Pata uchambuzi na ripoti',
    'dashboard.manageProfile': 'Simamia Wasifu',
    'dashboard.manageProfileDesc': 'Sasisha taarifa za wasifu wako',
    'dashboard.manageRulers': 'Simamia Viongozi',
    'dashboard.manageRulersDesc': 'Idhinisha na simamia viongozi wa jadi',
    'dashboard.systemDisputesDesc': 'Shughulikia utatuzi wa migogoro wa mfumo',
    'dashboard.userManagement': 'Usimamizi wa Watumiaji',
    'dashboard.userManagementDesc': 'Simamia watumiaji wa mfumo na ruhusa',
    'dashboard.systemSettings': 'Mipangilio ya Mfumo',
    'dashboard.systemSettingsDesc': 'Sanidi mipangilio ya mfumo',
    'dashboard.analytics': 'Uchambuzi',
    'dashboard.analyticsDesc': 'Ona uchambuzi na maarifa ya mfumo',
    'dashboard.recentActivity': 'Shughuli za Hivi Karibuni',
    'dashboard.systemAlerts': 'Taadhari za Mfumo',
    'dashboard.recentSystemActivity': 'Shughuli za Hivi Karibuni za Mfumo',
    'dashboard.newDisputeActivity': 'Migogoro mpya iliyowasilishwa na Mkuu Adebayo',
    'dashboard.culturalFestivalActivity': 'Tamasha la kitamaduni limepangwa mwezi ujao',
    'dashboard.newMembersActivity': 'Wanachama 5 wapya wamejiunga na jamii',
    'dashboard.highPriorityDispute': 'Migogoro ya kipaumbele cha juu inahitaji tahadhari',
    'dashboard.requiresImmediate': 'Inahitaji ukaguzi wa haraka',
    'dashboard.pendingRulerApproval': 'Maombi ya mkuu mpya yanasubiri idhini',
    'dashboard.awaitingReview': 'Yanasubiri ukaguzi wa utawala',
    'dashboard.systemMaintenance': 'Matengenezo ya mfumo yamepangwa',
    'dashboard.scheduledTonight': 'Yamepangwa usiku wa leo saa 2 asubuhi',
    'dashboard.newRulerApproved': 'Maombi ya mkuu mpya yameidhinishwa',
    'dashboard.newCommunityRegistered': 'Jamii mpya imesajiliwa katika mfumo',
    'dashboard.bulkUserImport': 'Uingizaji wa watumiaji wengi umekamilika',
    'dashboard.completedSuccessfully': 'Umekamilika kwa mafanikio',
    'dashboard.twoHoursAgo': 'Muda wa masaa 2 uliopita',
    'dashboard.oneHourAgo': 'Muda wa saa 1 iliyopita',
    'dashboard.oneDayAgo': 'Muda wa siku 1 iliyopita',
    'dashboard.threeDaysAgo': 'Muda wa siku 3 zilizopita',
    
    // Community Management
    'community.title': 'Usimamizi wa Jamii',
    'community.subtitle': 'Simamia jamii na falme za jadi',
    'community.loading': 'Inapakia jamii...',
    'community.traditionalCommunities': 'Jamii za Jadi',
    'community.addNew': 'Ongeza Mpya',
    'community.addNewCommunity': 'Ongeza Jamii Mpya',
    'community.addCommunity': 'Ongeza Jamii',
    'community.editCommunity': 'Hariri Jamii',
    'community.name': 'Jina la Jamii',
    'community.ruler': 'Mkuu',
    'community.location': 'Mahali',
    'community.description': 'Maelezo',
    'community.status': 'Hali',
    'community.active': 'Hai',
    'community.inactive': 'Haijaamilishwa',
    'community.members': 'wanachama',
    'community.add': 'Ongeza',
    'community.update': 'Sasisha',
    'community.cancel': 'Ghairi',
    'community.edit': 'Hariri',
    'community.delete': 'Futa',
    'community.confirmDelete': 'Una uhakika unataka kufuta jamii hii?',
    'community.noCommunities': 'Hakuna jamii zilizopatikana. Ongeza jamii yako ya kwanza ili uanze.',
    'community.quickActions': 'Vitendo vya Haraka',
    'community.importCommunities': 'Ingiza Jamii',
    'community.generateReport': 'Tengeneza Ripoti',
    'community.statistics': 'Takwimu',
    'community.totalCommunities': 'Jumla ya Jamii',
    'community.totalMembers': 'Jumla ya Wanachama',
    'community.activeCommunities': 'Jamii Hai',
    
    // Language
    'language.english': 'English',
    'language.french': 'Français',
    'language.spanish': 'Español',
    'language.arabic': 'العربية',
    'language.swahili': 'Kiswahili',
    'language.yoruba': 'Yorùbá',
    'language.igbo': 'Igbo',
    'language.hausa': 'Hausa',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Get language from localStorage or default to English
    return localStorage.getItem('atrc-language') || 'en';
  });

  const [translations, setTranslations] = useState(translationData[language] || translationData.en);

  useEffect(() => {
    // Update translations when language changes
    setTranslations(translationData[language] || translationData.en);
    // Save to localStorage
    localStorage.setItem('atrc-language', language);
  }, [language]);

  const t = (key) => {
    return translations[key] || key;
  };

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
  };

  const value = {
    language,
    changeLanguage,
    t,
    availableLanguages: [
      { code: 'en', name: 'English', flag: '🇺🇸' },
      { code: 'fr', name: 'Français', flag: '🇫🇷' },
      { code: 'es', name: 'Español', flag: '🇪🇸' },
      { code: 'sw', name: 'Kiswahili', flag: '🇹🇿' },
    ]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
